import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./shared/footer/footer";
import { Header } from "./shared/header/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SG SST",
  description: "Generated by Yenny",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        style={{background:"white"}}
      >
        

        {/* Contenido principal */}
        <main className="flex-grow" style={{}}>{children}</main>
  
        {/* Footer */}
        <footer >
           <Footer/>
        </footer>
      </body>
    </html>
  );
}
